CREATE TABLE spring_boot_demo.security_user (
  id          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username    VARCHAR(11) ,
  password    VARCHAR(64) NOT NULL,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY unique_username (username)
);

CREATE TABLE spring_boot_demo.security_role (
  id          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username    VARCHAR(11) NOT NULL,
  role        VARCHAR(11) NOT NULL,
  create_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
